# New-ChangelogIndex.ps1 - generate the day table in CHANGELOG/CHANGELOG_README.md
# from the day folders it indexes.
#
# WHY THIS EXISTS: rules/agent-topology-and-model-routing.md S5.2 - "shard before
# you lease... indexes should be generated from the directory they index rather
# than hand-appended." The changelog itself was sharded to one file per session on
# 2026-08-03 and stopped colliding; the INDEX above it was not, and became the
# second-most contended file in the repo (30 touches across the board repos). Its
# day row was one table cell that every session of that day appended a paragraph
# to - so on 2026-08-04 six sessions shared one cell and one of them could not
# write its sentence at all, and a third session had to pay the debt two minutes
# later (S5.2 incident #3).
#
# A generated row removes the contention instead of serializing it: the day row is
# now a link, a session count, and one line per session, all derived from the
# files on disk. Nobody hand-appends prose to a shared cell. Each session's line
# comes from its own file's "> **Summary:**" line, which sits next to the already
# mandatory "> **Branch:**" line and is owned by that session alone.
#
# The prose rollup for a day did not disappear - it lives where the convention
# already put it: CHANGELOG/YYYY-MM-DD/SUMMARY.md, written by the first session of
# a later day. The generator links it when it exists.
#
# Legacy flat days (CHANGELOG/YYYY-MM-DD.md, pre-2026-08-04) are NOT touched: they
# keep their hand-written rows in the static Archive table below the generated
# region. Nothing migrates - that is history, not drift.
#
#   New-ChangelogIndex.ps1                  # rewrite the region from the WORKING TREE
#   New-ChangelogIndex.ps1 -Check           # exit 1 if the region is stale (whole tree)
#   New-ChangelogIndex.ps1 -Staged          # rewrite it from the GIT INDEX
#   New-ChangelogIndex.ps1 -Check -Staged   # verify against the git index (pre-commit)
#
# Exit codes: 0 = written / already current, 1 = stale (-Check), 2 = error.
#
# -STAGED, AND WHY IT HAD TO MOVE BOTH HALVES AT ONCE (TODO_MUST item 6, closed
# 2026-08-15 by governance-backlog-sweep). Sync-AgentAssets.ps1 and Check-KbLinks.ps1
# got -Staged on 2026-08-12; this script deliberately did not, because it is not a
# checker - it WRITES the table it also VERIFIES. Scope only the -Check half and a
# session that regenerates from the working tree (picking up a sibling's untracked
# changelog file) then fails its own staged check: a false block strictly worse than
# the one being removed.
#
# So the source is chosen ONCE, in Get-DayModel, and both halves consume the model it
# returns. Get-DayRow no longer touches the disk at all. The two halves cannot read
# different inputs because there is only one place an input is read.
#
# WHAT IT FIXES (kb/dev/flows/lease.md S4c-i - the residual is a RACE, not a scope).
# The whole-tree check measures a moving target: the artifact can change between your
# regeneration and your commit, and the second failure looks identical to the first.
# Both observed blocks on 2026-08-13 are silent under -Staged - one was a sibling's
# UNTRACKED files (not in the index) and one was a sibling still EDITING its own
# changelog's Summary line in the working tree (the index holds the staged blob).
#
# WHAT IT DOES NOT FIX, stated rather than implied: the git index is shared and is not
# partitioned by path (S5). A sibling running `git add` inside your window still moves
# what you are checked against. That window is milliseconds rather than turns, and it
# is the same residual exposure every other -Staged gate here already carries; no
# script can close it, only a worktree per session can.
#
# ORDERING CHANGE - this is a workflow change, not just a flag. Under -Staged the
# generator reads the INDEX, so a session must `git add` its own changelog file BEFORE
# regenerating, not after:
#
#   git add CHANGELOG/<day>/<session>.md
#   powershell -File scripts\New-ChangelogIndex.ps1 -Staged
#   git add CHANGELOG/CHANGELOG_README.md
#   git commit -F <msg> -- <paths>
#
# Keep those four collapsed into one command per S4c-i: that remedy shrinks the
# residual window above and is not superseded by this flag.
#
# ASCII-only on purpose - Windows PowerShell 5.1 misparses BOM-less UTF-8
# (rules/hook-strategy.md wiring rule 3).

[CmdletBinding()]
param(
    [string]$RepoRoot = '',
    [switch]$Check,
    [switch]$Staged
)

$ErrorActionPreference = 'Stop'

$BeginMarker = '<!-- CHANGELOG-INDEX:BEGIN generated by scripts/New-ChangelogIndex.ps1 - do not hand-edit -->'
$EndMarker   = '<!-- CHANGELOG-INDEX:END -->'

# Changelog prose is full of em dashes and emoji. Windows PowerShell 5.1's
# Get-Content/Set-Content default to the ANSI codepage, which decodes a BOM-less
# UTF-8 file into mojibake and then writes the mojibake back - it corrupts every
# row it does not touch. Always go through .NET with an explicit BOM-less UTF-8:
# read decodes correctly (and strips a BOM if one is there), write adds none.
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

# House separators, spelled by code point so this file stays ASCII (see header).
$Sep   = ' ' + [char]0x00B7 + ' '   # middot, between entries
$Dash  = ' ' + [char]0x2014 + ' '   # em dash, between a session link and its summary

# ---------------------------------------------------------------- helpers

function Get-RepoRoot([string]$start) {
    $dir = if ($start) { Get-Item -LiteralPath $start } else { Get-Item -LiteralPath (Get-Location).Path }
    if (-not $dir.PSIsContainer) { $dir = $dir.Parent }
    while ($dir) {
        if (Test-Path (Join-Path $dir.FullName 'CHANGELOG')) { return $dir.FullName }
        $dir = $dir.Parent
    }
    return $null
}

# A session's own summary. Lives next to the mandatory Branch line, so it is written
# and self-checked by the same step that writes the file - and it is the ONLY thing
# this session contributes to the shared index.
#
# HARD-WRAPPED SUMMARIES ARE JOINED, not truncated (TODO_OPTIONAL/Tooling item 1,
# fixed 2026-08-14 by open-items-sweep). This used to return the first capture and
# nothing else, so everything after the first newline was dropped SILENTLY: the row
# rendered as valid markdown, the day count was right, and -Check passed, so a
# truncated row was indistinguishable from a short summary. Measured at the fix:
# 2 of the day-folder files hard-wrap, and BOTH their rows were cut mid-sentence -
# CHANGELOG/2026-08-14/rules-userrules-parity.md ended at "...should be" and
# 2026-08-10/c1-points-and-time-ingest.md at "...`derive-dont-stamp.md`".
#
# WHY JOIN RATHER THAN WARN. The convention is one physical line and the comment
# above used to say so, but every other file in this repo hard-wraps at ~100 columns
# and a markdown blockquote wraps naturally, so authors keep writing what they mean
# rather than what the parser wants. Making the author serve the tool is the same
# inversion rejected for Show-CandidateQueue.ps1's Status matcher on the same day.
# Joining is what the author meant, and it needs no new discipline from anyone.
#
# Takes the file's TEXT, not its path. That is deliberate: the read moved up into
# Get-DayModel so that the working-tree and index sources differ in exactly one place
# and this parser can never be pointed at a different input than the row builder.
function Get-SessionSummary([string]$text) {
    $lines = $text -split "`r?`n"

    # The Summary must appear in the header region; only the CONTINUATION scan runs
    # past it, so a long summary can no longer outgrow the search window.
    $start = -1
    $first = ''
    $limit = [Math]::Min(30, $lines.Count)
    for ($i = 0; $i -lt $limit; $i++) {
        if ($lines[$i] -match '^\s*>\s*\*\*Summary:\*\*\s*(.*?)\s*$') {
            $start = $i; $first = $Matches[1]; break
        }
    }
    if ($start -lt 0) { return '' }

    $parts = @()
    if ($first) { $parts += $first }
    for ($j = $start + 1; $j -lt $lines.Count; $j++) {
        $l = $lines[$j]
        if ($l -notmatch '^\s*>') { break }                        # blockquote ended (blank line, **Branch:**, ...)
        $cont = ($l -replace '^\s*>\s?', '').Trim()
        if ($cont -eq '') { break }                                # a bare '>' - paragraph break inside the quote
        if ($cont -match '^\*\*[^*]+:\*\*') { break }              # a DIFFERENT field in the same quote, not our text
        $parts += $cont
    }
    return (($parts -join ' ') -replace '\s+', ' ').Trim()
}

# A table cell cannot contain a raw '|'. Found live 2026-08-14 while fixing the
# truncation above: the 2026-08-12 row carried FOUR pipes where a valid row has
# three, because c8-ai-task-plans-ingest.md's summary contains
# `STATE_YOU_REACH | WORK_YOU_DO` - so that row had silently rendered an extra
# column since it was written. Nothing to do with wrapping, and worse than it, but
# joining continuation lines multiplies the chance of hitting it, so the escape
# ships with the join rather than after it. Already-escaped pipes are left alone so
# the function is idempotent.
function ConvertTo-CellSafe([string]$text) {
    if (-not $text) { return $text }
    return ($text -replace '(?<!\\)\|', '\|')
}

# THE single input read - see the -Staged note in the header. Returns day objects
# (newest first), each with Name / HasRollup / Files (Name + Text, sorted by name).
# Returns $null ONLY when the index was asked for and git could not answer; the caller
# then falls back to the working tree, which is the STRICTER answer, so an unreadable
# index can never silently switch the gate off (same contract as Check-KbLinks.ps1).
function Get-DayModel([string]$root, [string]$changelog, [bool]$fromIndex) {
    $dayPattern = '^\d{4}-\d{2}-\d{2}$'

    if (-not $fromIndex) {
        $dirs = @(Get-ChildItem -LiteralPath $changelog -Directory |
            Where-Object { $_.Name -match $dayPattern } |
            Sort-Object Name -Descending)
        $model = @()
        foreach ($d in $dirs) {
            $files = @(Get-ChildItem -LiteralPath $d.FullName -Filter *.md -File |
                Where-Object { $_.Name -ne 'SUMMARY.md' } |
                Sort-Object Name |
                ForEach-Object { @{ Name = $_.Name; Text = [IO.File]::ReadAllText($_.FullName, $Utf8NoBom) } })
            $model += @{
                Name      = $d.Name
                HasRollup = (Test-Path -LiteralPath (Join-Path $d.FullName 'SUMMARY.md'))
                Files     = $files
            }
        }
        return ,$model
    }

    # --- index source. `git show :<path>` reads the STAGED blob, so a sibling editing
    # its own changelog in the working tree is invisible here - which is the point.
    #
    # PowerShell 5.1 decodes native stdout with [Console]::OutputEncoding, which is the
    # ANSI codepage by default. Changelog prose is full of em dashes, section signs and
    # emoji, so decoding a blob as ANSI would mangle every one of them and the generated
    # region would differ from the working-tree answer on a correct tree - i.e. a false
    # STALE. Force UTF-8 for the duration and restore it, and if the console refuses the
    # assignment, give up on index scoping rather than return mojibake.
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    $prevEnc = $null
    try {
        try {
            $prevEnc = [Console]::OutputEncoding
            [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false)
        } catch { return $null }

        $lsFiles = & git -C $root -c core.quotepath=false -c core.safecrlf=false ls-files -- CHANGELOG
        if ($LASTEXITCODE -ne 0) { return $null }

        $byDay = @{}
        $rollups = @{}
        foreach ($l in @($lsFiles)) {
            if (-not $l) { continue }
            $p = [string]$l
            if ($p -notmatch '^CHANGELOG/(\d{4}-\d{2}-\d{2})/([^/]+\.md)$') { continue }
            $day = $Matches[1]; $name = $Matches[2]
            if ($name -eq 'SUMMARY.md') { $rollups[$day] = $true; continue }
            if (-not $byDay.ContainsKey($day)) { $byDay[$day] = @() }
            $byDay[$day] += $name
        }

        $model = @()
        foreach ($day in ($byDay.Keys + $rollups.Keys | Sort-Object -Unique -Descending)) {
            $names = @()
            if ($byDay.ContainsKey($day)) { $names = @($byDay[$day] | Sort-Object) }
            $files = @()
            foreach ($n in $names) {
                $blob = & git -C $root -c core.safecrlf=false show ":CHANGELOG/$day/$n"
                if ($LASTEXITCODE -ne 0) { return $null }
                $files += @{ Name = $n; Text = (@($blob) -join "`n") }
            }
            $model += @{ Name = $day; HasRollup = [bool]$rollups[$day]; Files = $files }
        }
        return ,$model
    } catch {
        return $null
    } finally {
        if ($null -ne $prevEnc) { try { [Console]::OutputEncoding = $prevEnc } catch { } }
        $ErrorActionPreference = $prevEap
    }
}

function Get-DayRow($day) {
    $rel = $day.Name

    $parts = @()
    $count = $day.Files.Count
    $parts += "**$count session$(if ($count -ne 1) { 's' })**"

    if ($day.HasRollup) { $parts += "[day rollup]($rel/SUMMARY.md)" }

    foreach ($f in $day.Files) {
        $label = [IO.Path]::GetFileNameWithoutExtension($f.Name)
        $link  = "[``$label``]($rel/$($f.Name))"
        $sum   = ConvertTo-CellSafe (Get-SessionSummary $f.Text)
        # No Summary line (a file written before this convention, or one that skipped
        # it): emit the bare link rather than inventing prose. The gap is visible.
        if ($sum) { $parts += "$link$Dash$sum" } else { $parts += $link }
    }

    $desc = $parts -join $Sep
    return "| [$rel]($rel/) | $desc |"
}

# ---------------------------------------------------------------- main

$root = Get-RepoRoot $RepoRoot
if (-not $root) { Write-Output 'FAIL: no CHANGELOG/ directory found above the current path.'; exit 2 }

$changelog = Join-Path $root 'CHANGELOG'
$readme    = Join-Path $changelog 'CHANGELOG_README.md'
if (-not (Test-Path -LiteralPath $readme)) { Write-Output "FAIL: no $readme"; exit 2 }

$scope = 'working tree'
$days  = $null
if ($Staged) {
    $days = Get-DayModel $root $changelog $true
    if ($null -eq $days) {
        Write-Output 'STAGED SCOPING UNAVAILABLE: could not read the git index - falling back to the whole tree.'
    } else {
        $scope = 'git index'
    }
}
if ($null -eq $days) { $days = Get-DayModel $root $changelog $false }

$text = [IO.File]::ReadAllText($readme, $Utf8NoBom)
# Emit the region in the line ending the file already uses, so a regeneration is
# not a whole-file diff.
$nl = if ($text -match "`r`n") { "`r`n" } else { "`n" }

$rows = @('| Date | Sessions |', '|------|----------|')
foreach ($d in $days) { $rows += (Get-DayRow $d) }
$generated = ($rows -join $nl)

$bi = $text.IndexOf($BeginMarker)
$ei = $text.IndexOf($EndMarker)
if ($bi -lt 0 -or $ei -lt 0 -or $ei -lt $bi) {
    Write-Output "FAIL: generated-region markers not found in $readme"
    Write-Output "  expected: $BeginMarker ... $EndMarker"
    exit 2
}

$head    = $text.Substring(0, $bi + $BeginMarker.Length)
$tail    = $text.Substring($ei)
$current = $text.Substring($bi + $BeginMarker.Length, $ei - ($bi + $BeginMarker.Length))
$desired = "$nl$nl$generated$nl$nl"

if ($current -eq $desired) {
    Write-Output "CHANGELOG index current: $($days.Count) day folder(s) (scope: $scope)."
    exit 0
}

if ($Check) {
    Write-Output "STALE: CHANGELOG/CHANGELOG_README.md generated region does not match the day folders (scope: $scope)."
    if ($scope -eq 'git index') {
        # The ordering matters and is the whole point of -Staged: regenerating from the
        # index before your own file is IN the index produces a table without your row.
        Write-Output '  fix: git add CHANGELOG/<day>/<session>.md'
        Write-Output '       powershell -File scripts\New-ChangelogIndex.ps1 -Staged'
        Write-Output '       git add CHANGELOG/CHANGELOG_README.md'
        Write-Output '  Keep those collapsed into one command (kb/dev/flows/lease.md S4c-i).'
    } else {
        Write-Output '  fix: powershell -File scripts\New-ChangelogIndex.ps1   (then git add the regenerated index)'
    }
    exit 1
}

[IO.File]::WriteAllText($readme, ($head + $desired + $tail), $Utf8NoBom)
Write-Output "Wrote CHANGELOG index: $($days.Count) day folder(s) (scope: $scope)."
exit 0
